name: flutter_erp
version: 2.2.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  form_validator:
  path: ^1.8.2
  http: ^0.13.5
  path_provider: ^2.0.11
  get_storage:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  
  get: ^4.6.5
  google_fonts: ^3.0.1
  url_strategy: ^0.2.0
  intl:
  dropdown_button2: ^2.0.0
  url_launcher: ^6.1.7
  file_picker: ^5.2.4
  syncfusion_flutter_charts: ^20.4.54
  rrule: ^0.2.10
  flutter_typeahead: ^4.3.7
  advanced_datatable: ^0.0.8
  syncfusion_flutter_datagrid: 20.4.54
  qr_flutter: ^4.0.0
  resource_manager:
    git:
      url: https://github.com/pratham-sarankar/resource_manager

dev_dependencies:
  build_runner:
  build_web_compilers:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

msix_config:
  display_name: Flutter Crm
  publisher_display_name: Pratham Sarankar
  publisher: Sarankar Developers
  identity_name: sarankar.erp
  languages: en-us
  capabilities: "internetClient"
  logo_path: C:\Users\yashs\OneDrive\Desktop\flutter_erp\assets\logo.png
