name: flutter_erp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  form_validator:
  path: ^1.8.2
  http: ^0.13.5
  path_provider: ^2.0.11
  get_storage:
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  fluttertoast:
  get: ^4.6.5
  google_fonts: ^3.0.1
  url_strategy: ^0.2.0
  intl: ^0.17.0
  dropdown_button2: ^1.9.2
  url_launcher: ^6.1.7
  file_picker: ^5.2.4

dev_dependencies:
  build_runner:
  build_web_compilers:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
